version: "3"
services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    command: gunicorn web.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    env_file:
      - .env
    volumes:
      - "/home/rogulin/media:/home/app/web/media"
  nginx:
    build: ./nginx
    ports:
      - 80:80
      - 443:443
    depends_on:
      - web
