version: "3"
services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    network_mode: "host"
    command: gunicorn app.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    env_file:
      - .env
    volumes:
      - static_volume:/home/app/web/static
      - "/home/rogulin/media:/home/app/web/media"
  nginx:
    build: ./nginx
    ports:
      - 80:80
      - 443:443
    depends_on:
      - web
    volumes:
     - static_volume:/home/app/web/static
     - media_volume:/home/app/web/media
volumes:
  static_volume:
  media_volume:
