# Generated by Django 4.1.4 on 2023-01-03 07:51

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        ('dictionary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_date', models.DateField(default=datetime.date.today, verbose_name='Дата открытия')),
                ('close_date', models.DateField(default=datetime.date.today, verbose_name='Дата закрытия')),
                ('mileage', models.IntegerField(default=0, verbose_name='Пробег')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.employee', verbose_name='Работник')),
                ('trailer', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='dictionary.trailer', verbose_name='Прицеп')),
                ('transport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.transport', verbose_name='Транспорт')),
            ],
            options={
                'verbose_name': 'Рабочий лист',
                'verbose_name_plural': 'Рабочие листы',
            },
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date(2023, 1, 3), verbose_name='Дата')),
                ('summ', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Сумма')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.incometype', verbose_name='Тип')),
                ('work_sheet', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='finance_operations.worksheet', verbose_name='Рабочий лист')),
            ],
            options={
                'verbose_name': 'Доход',
                'verbose_name_plural': 'Доходы',
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date(2023, 1, 3), verbose_name='Дата')),
                ('summ', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Сумма')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.expensetype', verbose_name='Тип')),
                ('work_sheet', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='finance_operations.worksheet', verbose_name='Рабочий лист')),
            ],
            options={
                'verbose_name': 'Расход',
                'verbose_name_plural': 'Расходы',
            },
        ),
    ]
