# Generated by Django 4.1.4 on 2023-01-03 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_operations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksheet',
            name='tonnage',
            field=models.IntegerField(default=0, verbose_name='Тоннаж'),
        ),
    ]
