# Generated by Django 4.1.4 on 2022-12-17 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0002_alter_employee_first_name_alter_employee_last_name_and_more'),
        ('finance_operations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.employee', verbose_name='Работник')),
                ('transport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.transport', verbose_name='Транспорт')),
            ],
            options={
                'verbose_name': 'Рабочий лист',
                'verbose_name_plural': 'Рабочие листы',
            },
        ),
        migrations.AddField(
            model_name='expense',
            name='work_sheet',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='finance_operations.worksheet', verbose_name='Рабочий лист'),
        ),
        migrations.AddField(
            model_name='income',
            name='work_sheet',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='finance_operations.worksheet', verbose_name='Рабочий лист'),
        ),
    ]
