# Generated by Django 4.1.4 on 2022-12-17 11:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_operations', '0002_worksheet_expense_work_sheet_income_work_sheet'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksheet',
            name='mileage',
            field=models.IntegerField(default=0, verbose_name='Пробег'),
        ),
        migrations.AddField(
            model_name='worksheet',
            name='passport_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата закрытия'),
        ),
    ]
