# Generated by Django 4.1.4 on 2023-02-24 19:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("finance_operations", "0003_alter_expense_date_alter_income_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="date",
            field=models.DateField(
                default=datetime.date(2023, 2, 24), verbose_name="Дата"
            ),
        ),
        migrations.AlterField(
            model_name="expense",
            name="work_sheet",
            field=models.ForeignKey(
                blank=True,
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="finance_operations.worksheet",
                verbose_name="Рабочий лист",
            ),
        ),
        migrations.AlterField(
            model_name="income",
            name="date",
            field=models.DateField(
                default=datetime.date(2023, 2, 24), verbose_name="Дата"
            ),
        ),
    ]
