# Generated by Django 4.1.4 on 2022-12-17 11:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_operations', '0003_worksheet_mileage_worksheet_passport_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='worksheet',
            old_name='passport_date',
            new_name='close_date',
        ),
        migrations.AddField(
            model_name='worksheet',
            name='open_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата открытия'),
        ),
    ]
