# Generated by Django 4.1.4 on 2022-12-26 10:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_operations', '0005_expense_date_income_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(default=datetime.date(2022, 12, 26), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='income',
            name='date',
            field=models.DateField(default=datetime.date(2022, 12, 26), verbose_name='Дата'),
        ),
    ]
