# Generated by Django 4.1.4 on 2023-01-02 19:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance_operations", "0006_alter_expense_date_alter_income_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="date",
            field=models.DateField(
                default=datetime.date(2023, 1, 2), verbose_name="Дата"
            ),
        ),
        migrations.AlterField(
            model_name="income",
            name="date",
            field=models.DateField(
                default=datetime.date(2023, 1, 2), verbose_name="Дата"
            ),
        ),
    ]
