# Generated by Django 4.1.4 on 2022-12-19 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance_operations', '0004_rename_passport_date_worksheet_close_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WayBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_date', models.DateField()),
                ('close_date', models.DateField()),
                ('worksheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance_operations.worksheet', verbose_name='Рабочий лист')),
            ],
            options={
                'verbose_name': 'Путевой лист',
            },
        ),
    ]
