# Generated by Django 4.1.4 on 2023-01-03 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0002_doctor'),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='waybill',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dictionary.doctor', verbose_name='Врач'),
        ),
    ]
