# Generated by Django 4.1.4 on 2023-03-13 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waybill',
            name='comment',
        ),
    ]
