# Generated by Django 4.1.4 on 2022-12-22 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dictionary", "0004_city_alter_employee_driving_license"),
        ("reports", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="waybill",
            options={
                "verbose_name": "Путевой лист",
                "verbose_name_plural": "Путевые листы",
            },
        ),
        migrations.CreateModel(
            name="Ride",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("distance", models.IntegerField(verbose_name="Расстояние")),
                (
                    "from_city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="from_city",
                        to="dictionary.city",
                        verbose_name="Начальная точка",
                    ),
                ),
                (
                    "to_city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="to_city",
                        to="dictionary.city",
                        verbose_name="Конечная точка",
                    ),
                ),
                (
                    "waybill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reports.waybill",
                        verbose_name="Путевой лист",
                    ),
                ),
            ],
            options={
                "verbose_name": "Рейс",
                "verbose_name_plural": "Рейсы",
            },
        ),
    ]
