# Generated by Django 4.1.4 on 2023-01-03 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0003_engineer'),
        ('reports', '0002_waybill_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='waybill',
            name='engineer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dictionary.engineer', verbose_name='Механик'),
        ),
    ]
