# Generated by Django 4.1.4 on 2023-03-13 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_remove_waybill_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='waybill',
            name='comment',
            field=models.TextField(default=None, null=True, verbose_name='Комментарий'),
        ),
    ]
