# Generated by Django 4.1.4 on 2023-03-13 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_waybill_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waybill',
            name='close_date',
            field=models.DateField(verbose_name='Дата закрытия'),
        ),
        migrations.AlterField(
            model_name='waybill',
            name='comment',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='waybill',
            name='open_date',
            field=models.DateField(verbose_name='Дата открытия'),
        ),
    ]
