# Generated by Django 4.1.4 on 2023-01-03 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0004_transport_model'),
        ('reports', '0003_waybill_engineer'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='cargo_name',
            field=models.CharField(default='', max_length=255, verbose_name='Название груза'),
        ),
        migrations.AddField(
            model_name='ride',
            name='orderer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='dictionary.company', verbose_name='Заказчик'),
        ),
        migrations.AddField(
            model_name='ride',
            name='ttn_number',
            field=models.CharField(default='', max_length=255, verbose_name='№ ТТН'),
        ),
    ]
