# Generated by Django 4.1.4 on 2023-03-13 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0003_city_area_city_name_city_region'),
        ('reports', '0004_alter_waybill_close_date_alter_waybill_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='from_cities',
            field=models.ManyToManyField(blank=True, default=None, related_name='from_cities', to='dictionary.city', verbose_name='Начальные точки'),
        ),
        migrations.AddField(
            model_name='ride',
            name='to_cities',
            field=models.ManyToManyField(blank=True, default=None, related_name='to_cities', to='dictionary.city', verbose_name='Конечные точки'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='from_city',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.PROTECT, related_name='from_city', to='dictionary.city', verbose_name='Начальная точка)'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='to_city',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.PROTECT, related_name='to_city', to='dictionary.city', verbose_name='Конечная точка)'),
        ),
    ]
