# Generated by Django 4.1.4 on 2023-01-04 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_ride_cargo_name_ride_orderer_ride_ttn_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='distance',
            field=models.IntegerField(verbose_name='Расстояние, км'),
        ),
    ]
