# Generated by Django 4.1.4 on 2023-03-13 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0003_city_area_city_name_city_region'),
        ('reports', '0004_alter_waybill_close_date_alter_waybill_comment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride',
            name='from_city',
        ),
        migrations.AddField(
            model_name='ride',
            name='from_city',
            field=models.ManyToManyField(related_name='from_city', to='dictionary.city', verbose_name='Начальная точка'),
        ),
    ]
