# Generated by Django 4.1.4 on 2023-03-13 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0003_city_area_city_name_city_region'),
        ('reports', '0005_remove_ride_from_city_ride_from_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride',
            name='to_city',
        ),
        migrations.AddField(
            model_name='ride',
            name='to_city',
            field=models.ManyToManyField(related_name='to_city', to='dictionary.city', verbose_name='Конечная точка'),
        ),
    ]
