# Generated by Django 4.1.4 on 2023-03-13 14:17

from django.db import migrations


def forward(apps, schema_editor):
    Waybill = apps.get_model("reports", "WayBill")
    for waybill in Waybill.objects.all():
        for ride in waybill.ride_set.all():
            ride.from_cities.add(ride.from_city)
            ride.to_cities.add(ride.to_city)

class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_auto_20230313_1716'),
    ]

    operations = [
        migrations.RunPython(forward)
    ]
