# Generated by Django 4.1.3 on 2022-12-14 09:51

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sur_name', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=255, verbose_name='Отчество')),
                ('passport_number', models.CharField(default='', max_length=255, verbose_name='Серия и номер паспорта')),
                ('passport_date', models.DateField(default=datetime.date.today, verbose_name='Дата выдачи')),
                ('passport_given_by', models.CharField(default='', max_length=255, verbose_name='Выдан (кем?)')),
                ('passport_filial_code', models.CharField(default='', max_length=20, verbose_name='Код подразделения')),
                ('passport_address', models.CharField(default='', max_length=255, verbose_name='Адрес прописки')),
            ],
            options={
                'verbose_name': 'Работник',
                'verbose_name_plural': 'Работники',
            },
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, verbose_name='Название')),
                ('reg_number', models.CharField(max_length=20, verbose_name='Регистрационный номер')),
                ('mileage', models.IntegerField(default=0, verbose_name='Пробег')),
                ('sts_number', models.CharField(default='', max_length=100, verbose_name='Номер СТС')),
                ('pts_number', models.CharField(default='', max_length=100, verbose_name='Номер ПТС')),
                ('vin', models.CharField(default='', max_length=100, verbose_name='VIN-Номер')),
                ('driver', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='dictionary.employee', verbose_name='Закрепленный водитель')),
            ],
            options={
                'verbose_name': 'Транспорт',
                'verbose_name_plural': 'Транспорт',
            },
        ),
    ]
