# Generated by Django 4.1.3 on 2022-12-14 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='first_name',
            field=models.CharField(default='', max_length=255, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='last_name',
            field=models.CharField(default='', max_length=255, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='sur_name',
            field=models.CharField(default='', max_length=255, verbose_name='Фамилия'),
        ),
    ]
