# Generated by Django 4.1.4 on 2023-03-13 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0002_remove_city_area_remove_city_name_remove_city_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='area',
            field=models.CharField(default='', max_length=255, verbose_name='Район'),
        ),
        migrations.AddField(
            model_name='city',
            name='name',
            field=models.CharField(default='', max_length=255, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='city',
            name='region',
            field=models.CharField(default='', max_length=255, verbose_name='Регион'),
        ),
    ]
