# Generated by Django 4.1.4 on 2022-12-19 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0002_alter_employee_first_name_alter_employee_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='driving_license',
            field=models.CharField(default='', max_length=255, verbose_name='Водительское удостоверение'),
        ),
        migrations.AddField(
            model_name='employee',
            name='phone',
            field=models.CharField(default='', max_length=255, verbose_name='Номер телефона'),
        ),
    ]
