# Generated by Django 4.1.4 on 2022-12-22 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dictionary", "0003_employee_driving_license_employee_phone"),
    ]

    operations = [
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="", max_length=255, verbose_name="Название"
                    ),
                ),
            ],
            options={
                "verbose_name": "Город",
                "verbose_name_plural": "Города",
            },
        ),
        migrations.AlterField(
            model_name="employee",
            name="driving_license",
            field=models.CharField(
                default="",
                max_length=255,
                verbose_name="Номер водительского удостоверения",
            ),
        ),
    ]
