# Generated by Django 4.1.4 on 2022-12-23 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dictionary", "0004_alter_employee_driving_license"),
        ("dictionary", "0004_city_alter_employee_driving_license"),
    ]

    operations = []
