# Generated by Django 4.1.4 on 2023-01-04 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0004_transport_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='driving_license_scan',
            field=models.ImageField(default='', upload_to='', verbose_name='Скан водительского удостоверения'),
        ),
        migrations.AddField(
            model_name='employee',
            name='passport_scan',
            field=models.ImageField(default='', upload_to='', verbose_name='Скан паспорта'),
        ),
        migrations.AlterField(
            model_name='company',
            name='fio',
            field=models.CharField(default='', help_text='Обязательно вводить через пробел!', max_length=255, verbose_name='ФИО'),
        ),
    ]
