# Generated by Django 4.1.4 on 2022-12-26 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0005_merge_20221223_2031'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(default='', max_length=255, verbose_name='ФИО')),
                ('inn', models.CharField(default='', max_length=255, verbose_name='ИНН')),
                ('ogrn', models.CharField(default='', max_length=255, verbose_name='ОГРН')),
                ('address', models.CharField(default='', max_length=255, verbose_name='Юридический адрес')),
                ('phone', models.CharField(default='', max_length=255, verbose_name='Номер телефона')),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организации',
            },
        ),
        migrations.CreateModel(
            name='Trailer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, verbose_name='Название')),
                ('reg_number', models.CharField(default='', max_length=255, verbose_name='Регистрационный номер')),
            ],
            options={
                'verbose_name': 'Прицеп',
                'verbose_name_plural': 'Прицепы',
            },
        ),
    ]
