# Generated by Django 4.1.4 on 2023-01-04 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0005_employee_driving_license_scan_employee_passport_scan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transport',
            name='sts_scan',
            field=models.ImageField(default='', upload_to='', verbose_name='Скан СТС'),
        ),
    ]
