# Generated by Django 4.1.4 on 2023-02-24 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dictionary", "0007_alter_employee_driving_license_scan_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transport",
            name="driver",
        ),
        migrations.AlterField(
            model_name="employee",
            name="driving_license_scan",
            field=models.FileField(
                blank=True,
                default="",
                upload_to="",
                verbose_name="Скан водительского удостоверения",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="passport_scan",
            field=models.FileField(
                blank=True, default="", upload_to="", verbose_name="Скан паспорта"
            ),
        ),
        migrations.AlterField(
            model_name="transport",
            name="mileage",
            field=models.IntegerField(blank=True, default=0, verbose_name="Пробег"),
        ),
        migrations.AlterField(
            model_name="transport",
            name="pts_number",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="Номер ПТС"
            ),
        ),
        migrations.AlterField(
            model_name="transport",
            name="sts_number",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="Номер СТС"
            ),
        ),
        migrations.AlterField(
            model_name="transport",
            name="sts_scan",
            field=models.FileField(
                blank=True, default="", upload_to="", verbose_name="Скан СТС"
            ),
        ),
        migrations.AlterField(
            model_name="transport",
            name="vin",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="VIN-Номер"
            ),
        ),
    ]
