# Generated by Django 4.1.4 on 2023-02-24 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dictionary", "0008_remove_transport_driver_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transport",
            name="sts_scan",
            field=models.ImageField(
                blank=True, default="", upload_to="", verbose_name="Скан СТС"
            ),
        ),
    ]
