# Generated by Django 4.1.4 on 2023-01-03 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dictionary', '0004_transport_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Firm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Фирма',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тип',
            },
        ),
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_date', models.DateField(verbose_name='Дата открытия')),
                ('close_date', models.DateField(verbose_name='Дата закрытия')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.company', verbose_name='Организация')),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='licenses.firm', verbose_name='Фирма')),
                ('trailer', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='dictionary.trailer', verbose_name='Прицеп')),
                ('transport', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='dictionary.transport', verbose_name='Транспорт')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='licenses.type', verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Страховка',
            },
        ),
    ]
