# Generated by Django 4.1.4 on 2023-01-03 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='insurance',
            options={'verbose_name': 'Страховка', 'verbose_name_plural': 'Страховки'},
        ),
    ]
