# Generated by Django 4.1.4 on 2023-01-04 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0002_alter_insurance_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurance',
            name='scan',
            field=models.ImageField(default='', upload_to='', verbose_name='Скан страховки'),
        ),
    ]
